name: Upload JAR to S3

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1

    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory contents
        run: ls -l target/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload JAR to S3
        run: aws s3 cp target/*.jar s3://my-ci-artifacts/ 



      - name: Build Docker image
        run: |
          docker build -t my-java-app --build-arg JAR_FILE=app.jar 
