name: Upload JAR to S3

on:
  push:
    branches:
      - master

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Upload JAR file to S3 bucket
        run: aws s3 cp target/*.jar s3://my-ci-artifacts/ --acl public-read --region $AWS_REGION
